# generated by datamodel-codegen:
#   filename:  ApiError.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Detail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    path: str
    message: str


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str
    message: str
    request_id: str | None = Field(None, alias="requestId")
    details: list[Detail] | None = None


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    error: Error
