# generated by datamodel-codegen:
#   filename:  AuditLogQuery.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class AuditLogQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    page: conint(ge=1, le=9007199254740991)
    page_size: conint(ge=1, le=200) = Field(..., alias="pageSize")
    actor_id: str | None = Field(None, alias="actorId")
    method: str | None = None
    from_: AwareDatetime | None = Field(None, alias="from")
    to: AwareDatetime | None = None
