# generated by datamodel-codegen:
#   filename:  AuditLogPage.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class TradingMode(StrEnum):
    backtest = "backtest"
    paper = "paper"
    live = "live"


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str
    at: AwareDatetime
    request_id: str = Field(..., alias="requestId")
    actor_id: str | None = Field(..., alias="actorId")
    role: str
    method: str
    url: str
    status_code: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias="statusCode"
    )
    trading_mode: TradingMode = Field(..., alias="tradingMode")


class AuditLogPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    items: list[Item]
    page: conint(ge=-9007199254740991, le=9007199254740991)
    page_size: conint(ge=-9007199254740991, le=9007199254740991) = Field(
        ..., alias="pageSize"
    )
    total: conint(ge=-9007199254740991, le=9007199254740991)
