# generated by datamodel-codegen:
#   filename:  BrokerTradeRecord.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, PositiveFloat, constr


class Side(StrEnum):
    buy = "buy"
    sell = "sell"


class BrokerTradeRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    broker_trade_id: str = Field(..., alias="brokerTradeId")
    instrument: constr(pattern=r"^[A-Z0-9]{2,6}_[A-Z0-9]{2,6}$")
    side: Side
    units: PositiveFloat
    open_price: float = Field(..., alias="openPrice")
    close_price: float | None = Field(..., alias="closePrice")
    realized_pl: float = Field(..., alias="realizedPl")
    opened_at: AwareDatetime = Field(..., alias="openedAt")
    closed_at: AwareDatetime | None = Field(..., alias="closedAt")
