# generated by datamodel-codegen:
#   filename:  BrokerPosition.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat, constr


class Side(StrEnum):
    buy = "buy"
    sell = "sell"


class BrokerPosition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    instrument: constr(pattern=r"^[A-Z0-9]{2,6}_[A-Z0-9]{2,6}$")
    side: Side
    units: PositiveFloat
    avg_price: float = Field(..., alias="avgPrice")
    unrealized_pl: float = Field(..., alias="unrealizedPl")
    broker_trade_ids: list[str] = Field(..., alias="brokerTradeIds")
