# generated by datamodel-codegen:
#   filename:  FXSession.json

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class User(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str
    email: EmailStr
    name: str | None = None
    image: AnyUrl | None = None


class FXSession(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    user: User
    step_up2_fa_at: AwareDatetime | None = Field(..., alias="stepUp2FAAt")
    expires: AwareDatetime
