# generated by datamodel-codegen:
#   filename:  HealthResponse.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class TradingMode(StrEnum):
    backtest = "backtest"
    paper = "paper"
    live = "live"


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    status: Literal["ok"]
    commit: str
    uptime: float
    trading_mode: TradingMode = Field(..., alias="tradingMode")
