# generated by datamodel-codegen:
#   filename:  Instrument.json

from __future__ import annotations

from pydantic import Field, RootModel, constr


class Instrument(RootModel[constr(pattern=r"^[A-Z0-9]{2,4}_[A-Z0-9]{2,4}$")]):
    root: constr(pattern=r"^[A-Z0-9]{2,4}_[A-Z0-9]{2,4}$") = Field(
        ..., title="Instrument"
    )
