# generated by datamodel-codegen:
#   filename:  OrderRequest.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat, constr


class Side(StrEnum):
    buy = "buy"
    sell = "sell"


class OrderRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    client_order_id: constr(min_length=1) = Field(..., alias="clientOrderId")
    instrument: constr(pattern=r"^[A-Z0-9]{2,6}_[A-Z0-9]{2,6}$")
    side: Side
    units: PositiveFloat
    type: Literal["market"]
    stop_loss_price: PositiveFloat | None = Field(None, alias="stopLossPrice")
    take_profit_price: PositiveFloat | None = Field(None, alias="takeProfitPrice")
