# generated by datamodel-codegen:
#   filename:  OrderStatus.json

from __future__ import annotations

from enum import StrEnum


class OrderStatus(StrEnum):
    filled = "filled"
    partial = "partial"
    rejected = "rejected"
