# generated by datamodel-codegen:
#   filename:  OrderResult.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class Status(StrEnum):
    filled = "filled"
    partial = "partial"
    rejected = "rejected"


class Broker(StrEnum):
    oanda = "oanda"


class OrderResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    client_order_id: str = Field(..., alias="clientOrderId")
    status: Status
    broker: Broker
    broker_order_id: str | None = Field(..., alias="brokerOrderId")
    broker_trade_id: str | None = Field(..., alias="brokerTradeId")
    requested_units: float = Field(..., alias="requestedUnits")
    filled_units: float = Field(..., alias="filledUnits")
    remainder_units: float = Field(..., alias="remainderUnits")
    price: float | None
    reason: str | None
