# generated by datamodel-codegen:
#   filename:  TradingMode.json

from __future__ import annotations

from enum import StrEnum


class TradingMode(StrEnum):
    backtest = "backtest"
    paper = "paper"
    live = "live"
