# generated by datamodel-codegen:
#   filename:  Trade.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Side(StrEnum):
    long = "long"
    short = "short"


class Mode(StrEnum):
    backtest = "backtest"
    paper = "paper"
    live = "live"


class Trade(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str
    instrument: constr(pattern=r"^[A-Z0-9]{2,4}_[A-Z0-9]{2,4}$")
    side: Side
    units: float
    mode: Mode
    opened_at: AwareDatetime = Field(..., alias="openedAt")
    closed_at: AwareDatetime | None = Field(..., alias="closedAt")
