# generated by datamodel-codegen:
#   filename:  WsClientMessage.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class WsClientMessage1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["subscribe"]
    channel: constr(pattern=r"^[a-zA-Z0-9:_-]+$", min_length=1, max_length=200)


class WsClientMessage2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["unsubscribe"]
    channel: constr(pattern=r"^[a-zA-Z0-9:_-]+$", min_length=1, max_length=200)


class WsClientMessage3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["ping"]


class WsClientMessage(
    RootModel[WsClientMessage1 | WsClientMessage2 | WsClientMessage3]
):
    root: WsClientMessage1 | WsClientMessage2 | WsClientMessage3 = Field(
        ..., title="WsClientMessage"
    )
