# generated by datamodel-codegen:
#   filename:  WsServerMessage.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class WsServerMessage1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["subscribed"]
    channel: constr(pattern=r"^[a-zA-Z0-9:_-]+$", min_length=1, max_length=200)


class WsServerMessage2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["unsubscribed"]
    channel: constr(pattern=r"^[a-zA-Z0-9:_-]+$", min_length=1, max_length=200)


class WsServerMessage3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["pong"]


class WsServerMessage4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["event"]
    channel: constr(pattern=r"^[a-zA-Z0-9:_-]+$", min_length=1, max_length=200)
    payload: Any
    at: AwareDatetime


class WsServerMessage5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["error"]
    code: str
    message: str


class WsServerMessage(
    RootModel[
        WsServerMessage1
        | WsServerMessage2
        | WsServerMessage3
        | WsServerMessage4
        | WsServerMessage5
    ]
):
    root: (
        WsServerMessage1
        | WsServerMessage2
        | WsServerMessage3
        | WsServerMessage4
        | WsServerMessage5
    ) = Field(..., title="WsServerMessage")
