"""BE-131 (Python side) — envelope decrypt parity with the Node sealer.

NODE_SEALED_ENVELOPE below was generated by the ACTUAL TS implementation
(apis/node-api/src/crypto/credentials.ts sealCredentials) with the dev key and
a fixed IV — it pins cross-language wire-format parity, not just a Python
round-trip."""

from __future__ import annotations

import base64
import json
import os

import pytest
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from app.execution.credentials import (
    CredentialError,
    open_credentials,
    parse_encryption_key,
)

# Dev key from .env.example (base64 of 32 bytes) — never used in prod.
DEV_KEY_B64 = "ZGV2LW9ubHktY3JlZGVudGlhbHMta2V5LTMyYnl0ZXM="

# Sealed by the Node implementation: payload
# {"apiToken":"oanda-test-token-1234","accountId":"101-004-1234567-001","note":"fixture"}
NODE_SEALED_ENVELOPE = (
    "v1:AAECAwQFBgcICQoL0gyiOfiD9OvnMC2M3SxJBKDRIXw7er2Bh1okVteB6Fpl"
    "stPWefMGa1llpsiXZ5k8FVeQAqLykLjPhO1aPFwixZqN37OIKsOYSf4EjoBNqn8b"
    "ktHk6ChtnWWyYp3EYh8KMXKhlLJDHA=="
)


def _seal(payload: dict[str, object], key: bytes) -> str:
    """Python-side sealer used only for tamper fixtures — mirrors the Node
    wire format: v1:base64(iv ‖ tag ‖ ct), AAD fx-broker-credentials:v1."""
    iv = os.urandom(12)
    ct_and_tag = AESGCM(key).encrypt(iv, json.dumps(payload).encode(), b"fx-broker-credentials:v1")
    ct, tag = ct_and_tag[:-16], ct_and_tag[-16:]
    return "v1:" + base64.b64encode(iv + tag + ct).decode()


def test_parse_encryption_key_accepts_32_bytes() -> None:
    assert len(parse_encryption_key(DEV_KEY_B64)) == 32


@pytest.mark.parametrize("bad", ["not-base64!!!", base64.b64encode(b"short").decode()])
def test_parse_encryption_key_rejects_bad_keys(bad: str) -> None:
    with pytest.raises(CredentialError):
        parse_encryption_key(bad)


def test_opens_node_sealed_envelope() -> None:
    """The cross-language pin: an envelope sealed by the TS code opens here."""
    creds = open_credentials(NODE_SEALED_ENVELOPE, parse_encryption_key(DEV_KEY_B64))
    assert creds.api_token == "oanda-test-token-1234"
    assert creds.account_id == "101-004-1234567-001"
    assert creds.raw["note"] == "fixture"  # extras preserved


def test_round_trip_python_sealed() -> None:
    key = parse_encryption_key(DEV_KEY_B64)
    envelope = _seal({"apiToken": "t", "accountId": "a"}, key)
    creds = open_credentials(envelope, key)
    assert (creds.api_token, creds.account_id) == ("t", "a")


def test_wrong_key_fails_authentication() -> None:
    other = base64.b64encode(b"another-32-byte-key-for-testing!").decode()
    with pytest.raises(CredentialError, match="authentication"):
        open_credentials(NODE_SEALED_ENVELOPE, parse_encryption_key(other))


def test_tampered_ciphertext_fails() -> None:
    head, body = NODE_SEALED_ENVELOPE.split(":", 1)
    raw = bytearray(base64.b64decode(body))
    raw[-1] ^= 0xFF
    tampered = f"{head}:{base64.b64encode(bytes(raw)).decode()}"
    with pytest.raises(CredentialError, match="authentication"):
        open_credentials(tampered, parse_encryption_key(DEV_KEY_B64))


@pytest.mark.parametrize(
    "envelope",
    ["v2:AAAA", "no-colon", "v1:", "v1:AAAA"],  # bad version / shape / truncated
)
def test_malformed_envelopes_rejected(envelope: str) -> None:
    with pytest.raises(CredentialError):
        open_credentials(envelope, parse_encryption_key(DEV_KEY_B64))


def test_missing_payload_field_rejected() -> None:
    key = parse_encryption_key(DEV_KEY_B64)
    envelope = _seal({"apiToken": "only-token"}, key)
    with pytest.raises(CredentialError, match="accountId"):
        open_credentials(envelope, key)
