# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto_gen import quant_pb2 as quant__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPipeline = channel.unary_unary(
                '/fx.quant.v1.QuantService/RunPipeline',
                request_serializer=quant__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=quant__pb2.RunPipelineResponse.FromString,
                _registered_method=True)
        self.SizePosition = channel.unary_unary(
                '/fx.quant.v1.QuantService/SizePosition',
                request_serializer=quant__pb2.SizePositionRequest.SerializeToString,
                response_deserializer=quant__pb2.SizePositionResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/fx.quant.v1.QuantService/Predict',
                request_serializer=quant__pb2.PredictRequest.SerializeToString,
                response_deserializer=quant__pb2.PredictResponse.FromString,
                _registered_method=True)


class QuantServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RunPipeline(self, request, context):
        """Full deterministic pipeline for one closed bar: features → regime →
        candidate + calibrated P(profitable). H1 budget: 30s (system design §2.2);
        the Node caller wraps this in a circuit breaker (BE-068, timeout → HOLD).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SizePosition(self, request, context):
        """Vol-targeted position sizing (Kelly-capped) for a candidate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Meta-model P(profitable) with calibration metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=quant__pb2.RunPipelineRequest.FromString,
                    response_serializer=quant__pb2.RunPipelineResponse.SerializeToString,
            ),
            'SizePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SizePosition,
                    request_deserializer=quant__pb2.SizePositionRequest.FromString,
                    response_serializer=quant__pb2.SizePositionResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=quant__pb2.PredictRequest.FromString,
                    response_serializer=quant__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fx.quant.v1.QuantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fx.quant.v1.QuantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.QuantService/RunPipeline',
            quant__pb2.RunPipelineRequest.SerializeToString,
            quant__pb2.RunPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SizePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.QuantService/SizePosition',
            quant__pb2.SizePositionRequest.SerializeToString,
            quant__pb2.SizePositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.QuantService/Predict',
            quant__pb2.PredictRequest.SerializeToString,
            quant__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExecutionServiceStub:
    """─── BE-050…052 — ExecutionService (Step 2.2) ───────────────────────────────
    Node orchestrates; Python owns broker I/O via the QN-030 adapter seam.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/fx.quant.v1.ExecutionService/PlaceOrder',
                request_serializer=quant__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=quant__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.CloseTrade = channel.unary_unary(
                '/fx.quant.v1.ExecutionService/CloseTrade',
                request_serializer=quant__pb2.CloseTradeRequest.SerializeToString,
                response_deserializer=quant__pb2.CloseTradeResponse.FromString,
                _registered_method=True)
        self.ModifyTrade = channel.unary_unary(
                '/fx.quant.v1.ExecutionService/ModifyTrade',
                request_serializer=quant__pb2.ModifyTradeRequest.SerializeToString,
                response_deserializer=quant__pb2.ModifyTradeResponse.FromString,
                _registered_method=True)
        self.ListOpenPositions = channel.unary_unary(
                '/fx.quant.v1.ExecutionService/ListOpenPositions',
                request_serializer=quant__pb2.ListOpenPositionsRequest.SerializeToString,
                response_deserializer=quant__pb2.ListOpenPositionsResponse.FromString,
                _registered_method=True)
        self.GetTransactions = channel.unary_unary(
                '/fx.quant.v1.ExecutionService/GetTransactions',
                request_serializer=quant__pb2.GetTransactionsRequest.SerializeToString,
                response_deserializer=quant__pb2.GetTransactionsResponse.FromString,
                _registered_method=True)


class ExecutionServiceServicer:
    """─── BE-050…052 — ExecutionService (Step 2.2) ───────────────────────────────
    Node orchestrates; Python owns broker I/O via the QN-030 adapter seam.

    """

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOpenPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=quant__pb2.PlaceOrderRequest.FromString,
                    response_serializer=quant__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'CloseTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseTrade,
                    request_deserializer=quant__pb2.CloseTradeRequest.FromString,
                    response_serializer=quant__pb2.CloseTradeResponse.SerializeToString,
            ),
            'ModifyTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyTrade,
                    request_deserializer=quant__pb2.ModifyTradeRequest.FromString,
                    response_serializer=quant__pb2.ModifyTradeResponse.SerializeToString,
            ),
            'ListOpenPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOpenPositions,
                    request_deserializer=quant__pb2.ListOpenPositionsRequest.FromString,
                    response_serializer=quant__pb2.ListOpenPositionsResponse.SerializeToString,
            ),
            'GetTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactions,
                    request_deserializer=quant__pb2.GetTransactionsRequest.FromString,
                    response_serializer=quant__pb2.GetTransactionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fx.quant.v1.ExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fx.quant.v1.ExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionService:
    """─── BE-050…052 — ExecutionService (Step 2.2) ───────────────────────────────
    Node orchestrates; Python owns broker I/O via the QN-030 adapter seam.

    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.ExecutionService/PlaceOrder',
            quant__pb2.PlaceOrderRequest.SerializeToString,
            quant__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.ExecutionService/CloseTrade',
            quant__pb2.CloseTradeRequest.SerializeToString,
            quant__pb2.CloseTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.ExecutionService/ModifyTrade',
            quant__pb2.ModifyTradeRequest.SerializeToString,
            quant__pb2.ModifyTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOpenPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.ExecutionService/ListOpenPositions',
            quant__pb2.ListOpenPositionsRequest.SerializeToString,
            quant__pb2.ListOpenPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.ExecutionService/GetTransactions',
            quant__pb2.GetTransactionsRequest.SerializeToString,
            quant__pb2.GetTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
