# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto_gen import quant_pb2 as quant__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPipeline = channel.unary_unary(
                '/fx.quant.v1.QuantService/RunPipeline',
                request_serializer=quant__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=quant__pb2.RunPipelineResponse.FromString,
                _registered_method=True)
        self.SizePosition = channel.unary_unary(
                '/fx.quant.v1.QuantService/SizePosition',
                request_serializer=quant__pb2.SizePositionRequest.SerializeToString,
                response_deserializer=quant__pb2.SizePositionResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/fx.quant.v1.QuantService/Predict',
                request_serializer=quant__pb2.PredictRequest.SerializeToString,
                response_deserializer=quant__pb2.PredictResponse.FromString,
                _registered_method=True)


class QuantServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RunPipeline(self, request, context):
        """Full deterministic pipeline for one closed bar: features → regime →
        candidate + calibrated P(profitable). H1 budget: 30s (system design §2.2);
        the Node caller wraps this in a circuit breaker (BE-068, timeout → HOLD).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SizePosition(self, request, context):
        """Vol-targeted position sizing (Kelly-capped) for a candidate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Meta-model P(profitable) with calibration metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=quant__pb2.RunPipelineRequest.FromString,
                    response_serializer=quant__pb2.RunPipelineResponse.SerializeToString,
            ),
            'SizePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SizePosition,
                    request_deserializer=quant__pb2.SizePositionRequest.FromString,
                    response_serializer=quant__pb2.SizePositionResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=quant__pb2.PredictRequest.FromString,
                    response_serializer=quant__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fx.quant.v1.QuantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fx.quant.v1.QuantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.QuantService/RunPipeline',
            quant__pb2.RunPipelineRequest.SerializeToString,
            quant__pb2.RunPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SizePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.QuantService/SizePosition',
            quant__pb2.SizePositionRequest.SerializeToString,
            quant__pb2.SizePositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.quant.v1.QuantService/Predict',
            quant__pb2.PredictRequest.SerializeToString,
            quant__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
